name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.ycdev.nl/youngcapital/nyc-icons"
      env:
        GITLAB_HOSTNAME: "gitlab.ycdev.nl"
        GITLAB_USERNAME: "edwin"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "864"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
